### ISSUE TITLE
Whats the font used in the preview image?

### ISSUE THREAD

**Issue by mjarkk** [oh-my-fish/theme-nai#4]
In this image?
![](https://cloud.githubusercontent.com/assets/1272018/5961225/116d0a7a-a7d3-11e4-88a6-43da003ddc6c.png)

**Comment by noxxxxxious** [comment]
I've always come back to this due to failed attempts at finding what font this was. Today, I can finally lay my search to rest.
For anyone else that stumbles upon this, this font is called "Envy Code R" and can be found here:
https://damieng.com/blog/2008/05/26/envy-code-r-preview-7-coding-font-released/
